# Generated by Django 4.0.5 on 2022-07-05 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_as_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 57, 40, 334333)),
        ),
    ]
