# Generated by Django 4.0.5 on 2022-07-05 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_as_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 21, 5, 53, 381053)),
        ),
    ]
