# Generated by Django 4.0.5 on 2022-07-05 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_alter_as_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='as',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='as',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='as',
            name='MatOrganica',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='as',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 21, 15, 15, 371864)),
        ),
    ]
