# Generated by Django 4.0.5 on 2022-07-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0015_alter_as_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='as',
            name='date',
        ),
    ]
