# Generated by Django 4.0.5 on 2022-07-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_remove_as_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='MatOrganica',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='matOrganica'),
        ),
        migrations.AlterField(
            model_name='as',
            name='aluminioHidr',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='aluminioHidr'),
        ),
        migrations.AlterField(
            model_name='as',
            name='azufre',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='azufre'),
        ),
        migrations.AlterField(
            model_name='as',
            name='boro',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='boro'),
        ),
        migrations.AlterField(
            model_name='as',
            name='calcio',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='calcio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='cice',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='cice'),
        ),
        migrations.AlterField(
            model_name='as',
            name='cobre',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='cobre'),
        ),
        migrations.AlterField(
            model_name='as',
            name='conductividad',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='conductividad'),
        ),
        migrations.AlterField(
            model_name='as',
            name='fosforo',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='fosforo'),
        ),
        migrations.AlterField(
            model_name='as',
            name='hierro',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='hierro'),
        ),
        migrations.AlterField(
            model_name='as',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='as',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='as',
            name='magnesio',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='magnesio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='manganeso',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='manganeso'),
        ),
        migrations.AlterField(
            model_name='as',
            name='pH',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='as',
            name='potasio',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='potasio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='sodio',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='sodio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='zinc',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='zinc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
