# Generated by Django 4.0.5 on 2022-07-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_remove_as_matorganica'),
    ]

    operations = [
        migrations.AddField(
            model_name='as',
            name='MatOrganica',
            field=models.DecimalField(decimal_places=3, default=2.3, max_digits=8, verbose_name='MatOrganica'),
        ),
    ]
