# Generated by Django 4.0.5 on 2022-07-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0020_alter_as_matorganica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='as',
            old_name='latitude',
            new_name='Latitud',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='longitude',
            new_name='Logitud',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='MatOrganica',
            new_name='Materia_Organica',
        ),
    ]
