# Generated by Django 4.0.5 on 2022-07-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0021_rename_latitude_as_latitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='as',
            old_name='aluminioHidr',
            new_name='AluminioHidr',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='azufre',
            new_name='Azufre',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='boro',
            new_name='Boro',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='cice',
            new_name='CICE',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='calcio',
            new_name='Calcio',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='cobre',
            new_name='Cobre',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='conductividad',
            new_name='Conductividad',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='fosforo',
            new_name='Fosforo',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='hierro',
            new_name='Hierro',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='Logitud',
            new_name='Longitud',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='magnesio',
            new_name='Magnesio',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='manganeso',
            new_name='Manganeso',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='potasio',
            new_name='Potasio',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='sodio',
            new_name='Sodio',
        ),
        migrations.RenameField(
            model_name='as',
            old_name='zinc',
            new_name='Zinc',
        ),
    ]
