# Generated by Django 4.0.5 on 2022-07-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0023_alter_as_aluminiohidr_alter_as_azufre_alter_as_boro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='as',
            name='AluminioHidr',
        ),
        migrations.AddField(
            model_name='as',
            name='Aluminio_Hidrogeno',
            field=models.DecimalField(decimal_places=4, default=2.1, max_digits=6, verbose_name='Aluminio_Hidrogeno'),
        ),
    ]
