# Generated by Django 4.0.5 on 2022-07-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0024_remove_as_aluminiohidr_as_aluminio_hidrogeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='Aluminio_Hidrogeno',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Aluminio_Hidrogeno'),
        ),
    ]
