# Generated by Django 4.0.5 on 2022-07-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0026_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='Aluminio_Hidrogeno',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Aluminio_Hidrogeno'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Azufre',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Azufre'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Boro',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Boro'),
        ),
        migrations.AlterField(
            model_name='as',
            name='CICE',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='CICE'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Calcio',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Calcio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Cobre',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cobre'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Conductividad',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Conductividad'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Fosforo',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Fosforo'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Hierro',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Hierro'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Latitud',
            field=models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Longitud',
            field=models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Magnesio',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Magnesio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Manganeso',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Manganeso'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Materia_Organica',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Mat_Organica'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Potasio',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Potasio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Sodio',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Sodio'),
        ),
        migrations.AlterField(
            model_name='as',
            name='Zinc',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Zinc'),
        ),
        migrations.AlterField(
            model_name='as',
            name='pH',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='pH'),
        ),
    ]
